binary_sensor:
  - platform: template
    sensors:
      master_bedroom_windows:
        device_class: window
        value_template: >-
          {{
            is_state('binary_sensor.master_bedroom_right_window', 'on')
            or
            is_state('binary_sensor.master_bedroom_left_window', 'on') }}
