title: Main

views:
  - title: Home
    path: home
    icon: "mdi:home"
    badges: !include lovelace/home/badges.yaml
    cards: !include lovelace/home/cards.yaml
  - title: Living Room
    path: living-room
    type: custom:horizontal-layout
    icon: "mdi:sofa"
    cards: !include lovelace/living_room/cards.yaml
  - title: Kitchen
    path: kitchen
    type: custom:horizontal-layout
    icon: "mdi:chef-hat"
    cards: !include lovelace/kitchen/cards.yaml
  - title: Master Bedroom
    path: master-bedroom
    type: custom:horizontal-layout
    icon: "mdi:bed-empty"
    cards: !include lovelace/master_bedroom/cards.yaml
  - title: Kids Bedroom
    path: kids-bedroom
    type: custom:horizontal-layout
    icon: "mdi:bunk-bed"
    cards: !include lovelace/kids_bedroom/cards.yaml
