binary_sensor:
  - platform: template
    sensors:
      living_room_windows:
        device_class: window
        value_template: >-
          {{ is_state('binary_sensor.living_room_window_1', 'on')
              or is_state('binary_sensor.living_room_window_2', 'on')
              or is_state('binary_sensor.living_room_window_3', 'on')
              or is_state('binary_sensor.living_room_window_4', 'on')
              or is_state('binary_sensor.living_room_window_5', 'on')
              or is_state('binary_sensor.living_room_window_6', 'on')
              or is_state('binary_sensor.living_room_window_7', 'on')
              or is_state('binary_sensor.living_room_window_8', 'on') }}
