# Amazon Alexa provides a Smart Home API for richer home automation control
# https://www.home-assistant.io/integrations/alexa.smart_home/
#
alexa:
  smart_home:
    locale: en-GB

group:
  alexas:
    name: All Alexas
    entities:
      - media_player.alexa_kitchen
      - media_player.alexa_living_room
      - media_player.alexa_master_bedroom
      - media_player.alexa_move

sensor:
  - platform: template
    sensors:
      last_alexa:
        value_template: >
          {{ expand(states.group.alexas)
                | selectattr('attributes.last_called','eq',True)
                | map(attribute='entity_id') | first }}
