automation:
  - alias: Routine · Leaving home
    id: 064bff1a-f317-4de8-b7ee-fdd51a51787b
    trigger:
      platform: state
      entity_id: binary_sensor.anyone_home
      to: "off"
    action:
      - service: fan.turn_off
        entity_id: fan.living_room_airpurifier
      - service: fan.turn_off
        entity_id: fan.master_bedroom_airpurifier
      - service: light.turn_off
        entity_id: all
      - service: media_player.turn_off
        entity_id:
          - media_player.living_room
          - media_player.master_bedroom
          - media_player.move
          - media_player.tv
