input_boolean:
  meds_taken:
    name: Meds have been taken
    icon: mdi:pill

automation:
  - alias: Routine · Meds Reminder · Reset meds taken
    id: a1966081-20f2-4017-be8f-c23cfa7e9a61
    trigger:
      platform: time
      at: "00:01:00"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.meds_taken

  - alias: Routine · Meds Reminder · Mark meds as taken from button
    id: d7185891-c1ff-4b69-990d-dbf803f6dad8
    trigger:
      - platform: device
        domain: mqtt
        device_id: 9263077109169a95d7b7746fd6e61ab8
        type: action
        subtype: single
        discovery_id: 0x00158d0006727203 action_single
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.meds_taken
      - service: notify.mobile_app_android_arthur
        data:
          message: clear_notification
          data:
            tag: medication-reminder

  #
  # based on the following blueprint
  # https://community.home-assistant.io/t/advanced-medication-reminder/300137
  #
  - alias: Routine · Meds Reminder · Notify when meds have not been taken
    id: 03f2d047-9829-44d3-aad3-4d6ae9075c08
    trigger:
      - platform: time
        at: "09:18:00"
    condition:
      - condition: state
        entity_id: input_boolean.meds_taken
        state: "off"
    action:
      - alias: Notify until the medication has been taken
        repeat:
          while:
            - condition: state
              entity_id: input_boolean.meds_taken
              state: "off"
            - condition: state
              entity_id: person.arthur
              state: "home"
          sequence:
            - service: logbook.log
              data:
                name: "Meds Reminder"
                message: "Reminder sent"
                entity_id: input_boolean.meds_taken
            - service: notify.alexa_media_alexa_kitchen
              data:
                message: >-
                  {% if repeat.index == 1 %}
                    {{ "Arthur, you forgot to take your meds today!" }}
                  {% elif repeat.index == 2 %}
                    {{ "Arthur forgot to take his meds today!" }}
                  {% elif repeat.index == 3 %}
                    {{ "Arthur, take your meds!" }}
                  {% elif repeat.index == 4 %}
                    {{ "Arthur, are you ok? You haven't taken your meds today!" }}
                  {% else %}
                    {{ "Arthur, are you listening to me? Take. Your. Meds! Now!" }}
                  {% endif %}
                data:
                  type: tts
            - service: notify.mobile_app_android_arthur
              data:
                title: "Meds Reminder"
                message: >-
                  {% if repeat.index <= 2 %}
                    {{ "Take your meds!" }}
                  {% else %}
                    {{ "Are you alive? Take your meds!" }}
                  {% endif %}
                data:
                  actions:
                    - title: "Taken"
                      action: taken
                    - title: "Ask later"
                      action: later
                    - title: "Skip"
                      action: skip
                  tag: medication-reminder
            - wait_for_trigger:
                platform: event
                event_type: mobile_app_notification_action
              timeout:
                minutes: 120
            - choose:
                - conditions: "{{ wait.trigger.event.data.action == 'taken' }}"
                  sequence:
                    - service: input_boolean.turn_on
                      target:
                        entity_id: input_boolean.meds_taken
                    - service: logbook.log
                      data:
                        name: "Meds Reminder"
                        message: "Medication taken"
                        entity_id: input_boolean.meds_taken
                - conditions: "{{ wait.trigger.event.data.action == 'later' }}"
                  sequence:
                    - service: logbook.log
                      data:
                        name: "Meds Reminder"
                        message: "Reminder postponed"
                        entity_id: input_boolean.meds_taken
                    - delay:
                        minutes: 60
                - conditions: "{{ wait.trigger.event.data.action == 'skip' }}"
                  sequence:
                    - service: input_boolean.turn_on
                      target:
                        entity_id: input_boolean.meds_taken
                    - service: logbook.log
                      data:
                        name: "Meds Reminder"
                        message: "Reminder skipped"
                        entity_id: input_boolean.meds_taken
              default:
                - service: notify.mobile_app_android_arthur
                  data:
                    message: clear_notification
                    data:
                      tag: medication-reminder
                - service: logbook.log
                  data:
                    name: "Meds Reminder"
                    message: "Notification timed out"
                    entity_id: input_boolean.meds_taken
