binary_sensor:
  - platform: template
    sensors:
      both_in_bed:
        friendly_name: Both in Bed
        value_template: >-
          {{ is_state("binary_sensor.arthur_in_bed", "on")
          and is_state("binary_sensor.suellen_in_bed", "home") }}
        device_class: occupancy
        icon_template: mdi:bed

automation:
  - alias: Routine 路 Sleep 路 Good Night
    id: 8190e95a-0ccc-4f81-9464-f3dbc4353f16
    trigger:
      - platform: state
        entity_id: binary_sensor.both_in_bed
        to: "on"
        for:
          seconds: 30
    condition:
      condition: template
      alias: "when is dark"
      value_template: >-
        {{ state_attr("sun.sun", "elevation") < -6 }}
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.house_mode
        data:
          option: night

  - alias: Routine 路 Sleep 路 Good Morning
    id: 4f803078-a6c9-4d3f-a783-a7ae07187fe1
    trigger:
      - platform: state
        entity_id: binary_sensor.both_in_bed
        to: "off"
        for:
          minutes: 15
    condition:
      - condition: sun
        after: sunrise
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.house_mode
        data:
          option: day
